complexity:
  LongMethod:
    threshold: 60
    ignoreAnnotated: [ 'Composable' ]
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 8
    ignoreAnnotated: [ 'Composable' ]
  CyclomaticComplexMethod:
    threshold: 15
    ignoreAnnotated: [ 'Composable' ]
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 40
    thresholdInObjects: 15
  NestedBlockDepth:
    threshold: 6

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: [ 'Composable' ]
  VariableNaming:
    active: true
  ClassNaming:
    active: true
  ConstructorParameterNaming:
    active: true

style:
  ReturnCount:
    max: 6
  MagicNumber:
    active: false
  UnusedPrivateMember:
    active: true
  ForbiddenComment:
    active: true
    comments: [ 'TODO:', 'FIXME:', 'HACK:' ]
  NoTabs:
    active: true
  MaxLineLength:
    maxLineLength: 160
    excludeImportStatements: true

exceptions:
  TooGenericExceptionCaught:
    active: false

coroutines:
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
